# Generated by Django 5.2.13 on 2026-04-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_seed_import_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importprofile',
            name='format',
            field=models.CharField(choices=[('csv', 'CSV'), ('ofx', 'OFX'), ('qfx', 'QFX'), ('xls', 'XLS')], max_length=8),
        ),
    ]
