# Generated by Django 5.2.13 on 2026-04-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_add_xls_import_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('import_hash__gt', '')), fields=('account', 'import_hash'), name='unique_account_import_hash'),
        ),
    ]
