# Generated by Django 5.2.13 on 2026-04-23 20:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_type", models.CharField(max_length=64)),
                ("owner_id", models.UUIDField()),
                ("filename", models.CharField(max_length=255)),
                ("mime", models.CharField(max_length=128)),
                ("size", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("encrypted_blob_ref", models.CharField(max_length=512)),
                ("dek_enc", models.BinaryField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner_type", "owner_id"],
                        name="core_attach_owner_t_cfa3ea_idx",
                    ),
                    models.Index(
                        fields=["sha256"], name="core_attach_sha256_53692d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("household_id", models.UUIDField(db_index=True)),
                ("user_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action", models.CharField(max_length=64)),
                ("entity", models.CharField(max_length=64)),
                ("before_hash", models.CharField(blank=True, max_length=64)),
                ("after_hash", models.CharField(blank=True, max_length=64)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["household_id", "at"],
                        name="core_auditl_househo_c6f380_idx",
                    ),
                    models.Index(
                        fields=["entity", "at"], name="core_auditl_entity_24def9_idx"
                    ),
                ],
            },
        ),
    ]
