# Generated by Django 5.2.13 on 2026-04-23 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceTask",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("days", "Every N days"),
                            ("weeks", "Every N weeks"),
                            ("months", "Every N months"),
                            ("years", "Every N years"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "cadence_interval",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="e.g. 3 + cadence=months = every three months.",
                    ),
                ),
                ("last_done", models.DateField(blank=True, null=True)),
                ("next_due", models.DateField(blank=True, db_index=True, null=True)),
                ("checklist_json", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_tasks",
                        to="accounts.household",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
