# Generated by Django 5.2.13 on 2026-04-24 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
        ('otp_totp', '0003_add_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPDeviceSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapped_dek', models.BinaryField()),
                ('ciphertext', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secret', to='otp_totp.totpdevice')),
            ],
        ),
    ]
